version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env
    container_name: api-gateway

  cart-service:
    build:
      context: ./cart-service
    ports:
      - "8086:8086"
    env_file:
      - ./cart-service/.env
    container_name: cart-service

  order-service:
    build:
      context: ./order-service
    ports:
      - "8082:8082"
    env_file:
      - ./order-service/.env
    container_name: order-service

  file-service:
    build:
      context: ./file-service
    ports:
      - "8085:8085"
    env_file:
      - ./file-service/.env
    container_name: file-service

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "8084:8084"
    env_file:
      - ./payment-service/.env
    container_name: payment-service

  product-service:
    build:
      context: ./product-service
    ports:
      - "8081:8081"
    env_file:
      - ./product-service/.env
    container_name: product-service

  user-service:
    build:
      context: ./user-service
    ports:
      - "8083:8083"
    env_file:
      - ./user-service/.env
    container_name: user-service
