version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sampleuser
      POSTGRES_PASSWORD: samplepassword
      POSTGRES_DB: sampledb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: sampleuser
      DB_PASSWORD: samplepassword
      DB_NAME: sampledb

volumes:
  pgdata:
